[viewer]
    Titile="AnyWiki"
    Logo="/resource/images/logo.png"
    Navigation = ["首页","/","Go语言","/golang","归档","/pigeonhole","关于","/about"]
    Bilibili =""
    Zhihu=""
    Avatar = ""
    UserName="tom"
    UserDesc = "英俊"
[system]
    CdnUrl=""
    QiniuSecretKey=""
    QiniuAccessKey=""
    Valine=true
    ValinAppid=""
    ValineServerURL=""
